#!/bin/sh
# Execute lint on files that have been changed.

cd "$(dirname "$0")/.."

export files="$(git diff $(git merge-base origin/master HEAD) --diff-filter=d --name-only | grep -e '\.py$')"
echo '================================================='
echo '=                FILES CHANGED                  ='
echo '================================================='
if [ -z "$files" ] ; then
  echo "No python file changed.  Have they been staged?"
  exit
fi
printf "%s\n" $files
echo "================"
echo "LINT with flake8"
echo "================"
flake8 --doctests $files
echo "================"
echo "LINT with pylint"
echo "================"
pylint $(echo "$files" | grep -v '^tests.*')
echo
